---
- hosts: testes
  remote_user: root
  tasks:
  - name: Instalação de ferramentas básicas em sistemas Linux
    package:
      name: {{item}}
      state: present
        item:
          - curl
          - htop
          - vim-tiny
          - wget
          - nmap
          - tar
          - zip
          - unzip
