---
- hosts: testes 
  remote_user: root
  tasks:
  - name: Instalação de ferramentas básicas em sistemas Linux
    action: apt pkg={{item}}  state=installed
    with_items:
        - curl
        - htop
        - vim-tiny
        - wget
        - nmap
        - tar
        - zip
        - unzip
