---
- hosts: testes
  remote_user: root
  vars_files:
    - vars.yml

  tasks:
  - name: Instalação de ferramentas básicas em sistemas APT
    apt:
      name: "{{ packages }}"
      state: present
      install_recommends: yes
