---
- hosts: testes
  remote_user: root
  vars_files:
    - vars.yml

  tasks:
  - name: Instalação de ferramentas básicas em sistemas Linux
    package:
      name: "{{ packages }}"
      state: present
      install_recommends: yes
